# Continuous Integration (CI) to build PW.ZedGraph
# using the .NET CLI on Azure Pipelines.

# Triggered when pushing to the "master"
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - .gitignore
    - CHANGELOG.md
    - License-LGPL.txt
    - logo-200x200.png
    - README.md
    - ToDo.txt

# Pipeline name
name: PW.ZedGraph.CI.$(Build.BuildId)

# Global variables
variables:
  vmImage: windows-2022
  libProjects: |
    **/ZedGraph/*.csproj
    **/ZedGraph.WinForms/*.csproj
  buildConfiguration: Release

jobs:
- job: Build
  displayName: Build PW.ZedGraph
  pool:
    vmImage: $(vmImage)
  steps:
  # Build and pack PW.ZedGraph
  - task: DotNetCoreCLI@2
    displayName: Build PW.ZedGraph
    inputs:
      command: custom
      custom: pack
      projects: $(libProjects)
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) -p:CIBuildId=$(Build.BuildId)'
  # Publish to pipeline artifacts
  - task: PublishPipelineArtifact@1
    displayName: Publish library to pipeline artifacts
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)
      artifactName: PW.ZedGraph
