# Continuous Integration (CI) for PW.ZedGraph

# Triggered when pushing to the "master" or "develop" branch
trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  tags:
    include:
    - 'v*'
  paths:
    exclude:
    - .gitignore
    - CHANGELOG.md
    - License-LGPL.txt
    - logo-200x200.png
    - README.md
    - ToDo.txt

# Use templates from the Utilities/PipelinesTemplates repository
resources:
  repositories:
  - repository: PipelinesTemplates
    type: git
    name: Utilities/PipelinesTemplates
    ref: refs/tags/v2.1.0

# Pipeline name
name: PW.ZedGraph.$(Build.BuildId)

stages:
- stage: Build
  jobs:
  - template: /DotNet/Build+Test.yml@PipelinesTemplates
    parameters:
      projectTitle: PW.ZedGraph
      vmImage: windows-latest
      setVersionFromGitTag: true
      libraryTitle: Libraries
      libraryProjects: |
        **/ZedGraph/*.csproj
        **/ZedGraph.WinForms/*.csproj

# Only publish package(s) from a version-tagged commit
- ${{ if contains(variables['Build.SourceBranch'], 'refs/tags/v') }}:
  - stage: Publish
    jobs:
    - template: /DotNet/PublishNuGet.yml@PipelinesTemplates
      parameters:
        projectTitle: PW.ZedGraph
        packageTitle: Packages
        environment: Publish-PW_ZedGraph-Env
        packagesToPublish: |
          **/PW.ZedGraph.*.nupkg
