# Continuous Integration (CI) and Continuous Delivery (CD) for PW.ZedGraph

# Triggered when pushing to the "master" or "develop" branch
trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    - .gitignore
    - CHANGELOG.md
    - License-LGPL.txt
    - logo-200x200.png
    - README.md
    - ToDo.txt

# Triggered when opening a pull request (or pushing changes to it)
pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - .gitignore
    - CHANGELOG.md
    - License-LGPL.txt
    - logo-200x200.png
    - README.md
    - ToDo.txt

# Use templates from the Utilities/PipelinesTemplates repository
resources:
  repositories:
  - repository: PipelinesTemplates
    type: git
    name: Utilities/PipelinesTemplates

# Pipeline name
name: PW.ZedGraph.$(Build.BuildId)

stages:
- stage: Build
  jobs:
  - template: /DotNet/Build+Test.yml@PipelinesTemplates
    parameters:
      projectTitle: PW.ZedGraph
      vmImage: windows-latest
      libraryTitle: Libraries
      libraryProjects: |
        **/ZedGraph/*.csproj
        **/ZedGraph.WinForms/*.csproj

# Only publish package(s) from the main, master or a release branch
- ${{ if or(in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')) }}:
  - stage: Publish
    jobs:
    - template: /DotNet/PublishNuGet.yml@PipelinesTemplates
      parameters:
        projectTitle: PW.ZedGraph
        packageTitle: Packages
        environment: Publish-PW_ZedGraph-Env
        packagesToPublish: |
          **/PW.ZedGraph.*.nupkg
